import ThemeProviderCard from '@/common/ThemeProviderCard';
import './globals.css';
import { Poppins } from 'next/font/google';
import Footer from '@/components/footer/Footer';
import Header from '@/components/header/Header';

const poppins = Poppins({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <ThemeProviderCard>
        <body className={poppins.className}>
          <Header />
          {children}
          <Footer />
        </body>
      </ThemeProviderCard>
    </html>
  );
}
